// DocumentData.js
const DOCUMENT_DATA = [
    { id: 1, title: "Project Plan", category: "Planning", author: "John Doe", date: "2025-03-01", status: "Completed", format: "PDF", size: "1.2 MB", content: "# Project Plan\n\n## Executive Summary\nThis project aims to deliver a new customer portal by Q3 2025. The portal will provide enhanced analytics and reporting capabilities.\n\n## Timeline\n- Research phase: 4 weeks\n- Design phase: 6 weeks\n- Development phase: 12 weeks\n- Testing phase: 4 weeks\n- Deployment: 2 weeks\n\n## Budget\nTotal allocated budget: $250,000\n- Personnel: $180,000\n- Infrastructure: $40,000\n- Software licenses: $20,000\n- Contingency: $10,000" },
    { id: 2, title: "Budget Report", category: "Finance", author: "Jane Smith", date: "2025-02-15", status: "Pending", format: "Excel", size: "2.5 MB", content: "# Q1 2025 Budget Report\n\n## Department Allocation\n- Marketing: $125,000\n- R&D: $250,000\n- Operations: $180,000\n- Sales: $210,000\n\n## YoY Comparison\nTotal budget increased by 12% compared to Q1 2024.\n\n## Forecasted ROI\nExpected return on marketing initiatives: 3.2x\nR&D projected value creation: $750,000" },
    { id: 3, title: "Meeting Minutes", category: "Meetings", author: "Alice Johnson", date: "2025-03-05", status: "Completed", format: "Word", size: "800 KB", content: "# Board Meeting Minutes - March 5, 2025\n\n## Attendees\n- CEO: Mark Williams\n- CFO: Sarah Johnson\n- CTO: James Lee\n- Board Members: Anna Smith, Robert Chen, Priya Patel\n\n## Agenda Items Discussed\n1. Q4 2024 Financial Review\n2. Product Roadmap Update\n3. International Expansion Plans\n4. Talent Acquisition Strategy\n\n## Key Decisions\n- Approved budget for APAC expansion\n- Deferred decision on new headquarters location\n- Approved new compensation structure" },
    { id: 4, title: "Design Mockups", category: "Design", author: "Bob Brown", date: "2025-02-20", status: "In Progress", format: "Image", size: "3.1 MB", content: "# Mobile App Redesign - Mockups\n\n## Home Screen\n[Image placeholder: Home screen with new navigation]\n\n## User Profile\n[Image placeholder: Updated user profile with achievements section]\n\n## Analytics Dashboard\n[Image placeholder: Data visualization with dark/light mode toggle]\n\n## Settings Menu\n[Image placeholder: Simplified settings interface with quick actions]" },
    { id: 5, title: "Sales Report", category: "Sales", author: "Charlie Green", date: "2025-03-03", status: "Completed", format: "PDF", size: "1.8 MB", content: "# Q1 2025 Sales Report\n\n## Regional Performance\n- North America: $2.4M (↑18%)\n- Europe: $1.8M (↑7%)\n- Asia: $1.2M (↑22%)\n- Australia: $0.6M (↑5%)\n\n## Top Performing Products\n1. Enterprise Solution: $1.5M\n2. Analytics Suite: $1.2M\n3. Mobile Platform: $0.8M\n\n## Sales Team Highlights\n- Team Alpha achieved 127% of target\n- New enterprise clients acquired: 14\n- Renewal rate: 94%" },
];

export default DOCUMENT_DATA;